#ifndef QUIRKY_SRC_SEARCH_POSITION_TRANSPOSITION_TABLE_H
#define QUIRKY_SRC_SEARCH_POSITION_TRANSPOSITION_TABLE_H

namespace q_search {

}  // namespace q_search

#endif  // QUIRKY_SRC_SEARCH_POSITION_TRANSPOSITION_TABLE_H
 
